### ISSUE TITLE
请问一下这个不支持谷歌浏览器吗？

### ISSUE THREAD

**Issue by Jason4774** [FirefoxBar/userscript#11]
请问一下这个不支持谷歌浏览器吗？
我试了一下，谷歌的不行，

**Comment by wenketel** [comment]
哪个脚本？

**Comment by Jason4774** [comment]
自动暂停视频播放的。



970852638@qq.com
 
发件人： 文科
发送时间： 2016-09-02 17:38
收件人： FirefoxBar/userscript
抄送： Jason; Author
主题： Re: [FirefoxBar/userscript] 请问一下这个不支持谷歌浏览器吗？ (#11)
哪个脚本？

**Comment by sylingd** [comment]
@linusyu
