### ISSUE TITLE
Tieba Quick Reply已失效或不可用

### ISSUE THREAD

**Issue by GaidenAAyuuyuu** [FirefoxBar/userscript#14]
涉及脚本：Tieba Quick Reply
Firefox版本：ESR 45.7
GreaseMonkey版本：3.9
重现步骤：发表和关闭按钮错位、点击发表后每次都是失败，显示回复失败!!
<img width="601" alt="2017-02-06 16 24 13" src="https://cloud.githubusercontent.com/assets/18454790/22639365/baac8d30-ec88-11e6-863d-f7cd48894525.png">

问题截图（建议）：

**Comment by sylingd** [comment]
已确认，正在尝试修复

**Comment by sylingd** [comment]
已修复
