### ISSUE TITLE
Post Del Robot  新版贴吧下失效

### ISSUE THREAD

**Issue by tjsky** [FirefoxBar/userscript#18]
涉及脚本：Post Del Robot 
Firefox版本：51.0.1
GreaseMonkey版本：3.10
重现步骤：获取帖子列表后，代码无动作。
问题截图（建议）：

已经问题。
```
137   var fid = unsafeWindow.PageData.forum.id,
138	 kw = unsafeWindow.PageData.forum.name,
```
无效，应该是forum.forum_id和forum.forum_name

仅修改这两个地方不能使代码正常工作，

应该还有其他问题，望作者详查。

**Comment by sylingd** [comment]
经测试。PageData部分不存在问题。
已经尝试进行一些修复，请更新后测试
