### ISSUE TITLE
阅读模式不支持mathjax公式

### ISSUE THREAD

**Issue by jesseliu612** [FirefoxBar/userscript#19]
涉及脚本：Reading_Mode
Firefox版本：57.0.1 (32 位)
GreaseMonkey版本：--
重现步骤：任意支持的网站只要含有mathjax都无法在阅读模式中正常显示公式。
问题截图（建议）：加入mathjax支持。图略。

**Comment by sylingd** [comment]
mathjax格式太过复杂，不打算进行兼容，抱歉
