### ISSUE TITLE
关于Tieba_Blocked_Detect的两个特殊情况下的bug 

### ISSUE THREAD

**Issue by shitianshiwa** [FirefoxBar/userscript#20]
1.触发条件不明的特殊情况下，屏蔽样式会出错，我个人将'position: absolute;'改为'position: relative;''解决（https://github.com/FirefoxBar/userscript/blob/master/Tieba_Blocked_Detect/Tieba_Blocked_Detect.user.js#L167）
不过样子变了。（截图打了黑色遮罩）（问题贴子是整个被屏蔽了）
--
出问题的样子
![截图1](https://user-images.githubusercontent.com/54750485/64557167-f7013380-d37b-11e9-823a-cb75e9b719fb.png)

正常的样子

![截图2](https://user-images.githubusercontent.com/54750485/64557173-fa94ba80-d37b-11e9-8ea7-9a6402423f25.png)
--

我个人修改后的样子（我把屏蔽颜色也加深了，以方便快速观察）
![截图3](https://user-images.githubusercontent.com/54750485/64558164-4183af80-d37e-11e9-8d8a-2af95d33a8d5.png)

--
2.无用户名的贴吧账户无法正常使用这个脚本。即便补了名字，实测也只能触发楼中楼的贴子，主题贴列表和楼层仍没有反应。（我并不知道没补名字前能不能触发楼中楼的贴子，没测试）（使用百度app注册的无用户名小号测试）
我个人测试发现原因是事件无法被触发到（水平有限，可能并没找到真正的原因）（https://github.com/FirefoxBar/userscript/blob/master/Tieba_Blocked_Detect/Tieba_Blocked_Detect.user.js#L310）

**Comment by shitianshiwa** [comment]
1.样式还是用'position: absolute;'改为'position: relative;''，且把背景弄得更红些，方便快速上下翻。
2.问题应该基本解决。用portrait代替贴吧帐号用户名(http://tieba.baidu.com/f/user/json_userinfo),api参考(https://t.52fisher.cn/tb-remind.html)，不过我不确认这样写真的没有问题。
https://github.com/shitianshiwa/baidu-tieba-userscript/blob/master/%E8%B4%B4%E5%90%A7%E8%B4%B4%E5%AD%90%E5%B1%8F%E8%94%BD%E6%A3%80%E6%B5%8B/%E8%B4%B4%E5%90%A7%E8%B4%B4%E5%AD%90%E5%B1%8F%E8%94%BD%E6%A3%80%E6%B5%8B(%E9%9D%9E%E5%AE%98%E6%96%B9%E4%BF%AE%E6%94%B9)/%E8%B4%B4%E5%90%A7%E8%B4%B4%E5%AD%90%E5%B1%8F%E8%94%BD%E6%A3%80%E6%B5%8B(%E9%9D%9E%E5%AE%98%E6%96%B9%E4%BF%AE%E6%94%B9).user.js#L53

**Comment by shitianshiwa** [comment]
新增问题：主题贴检测在2019-9-27发现失效了
https://github.com/FirefoxBar/userscript/blob/master/Tieba_Blocked_Detect/Tieba_Blocked_Detect.user.js#L97
修改为：const threadIsNotExist = res => res.indexOf('您要浏览的贴子不存在') >= 0||res.indexOf('1970-1-1') >= 0;//2019-9-27修改判断条件，以修复判断主题贴屏蔽失效
可以解决

**Comment by ccloli** [comment]
hi，抱歉这么晚才回复，因为代码是托管在 group 下的，所以之前没有收到这个 issue 相关的提醒邮件，刚刚才注意到有这么个 issue。

其实之前在 GitHub 的动态页上看到你加了 follow（当时还去找了头像原图），然而 GitHub 并没有列出相关的 issue，所以这个 issue 就被无视了 = =

言归正传，感谢提供 bug 反馈，这里先做下回复吧：

1. 第一个感觉有点奇怪，代码中 `position: absolute` 的只是右上角的提示文本而已，因为无法基于父元素定位，所以给父元素套了个 `position: relative` 使其相对于父元素定位。这部分理论上是没有问题的，在很久以前写的样式里也有 `position: relative` 的处理，除非页面中又多了些奇怪的 `position` 定位，或者是其他样式或脚本的冲突之类的。不知可否提供一下有问题的帖子地址呢？

2. 确实没有考虑到用户名不存在的情况（贴吧现在的逻辑太奇怪了，居然还有没有用户名的情况）。`portrait` 确实是个不错的方案，不知道当时为什么没有注意到。`portrait` 不需要单独请求 API 获取，页面里的全局变量 `PageData.user` 里就有这个参数。就是这个参数继承了贴吧的混乱邪恶，贴吧页的 `portrait` 是类似上面的 API 那样带上 `?t=` 后缀的；而贴子页的不带，而是有一个独立的 `portrait_time` 参数……另外原来现在贴吧的 `portrait` 已经变成这种奇怪的格式了，以前还只是一个哈希值，甚至还能根据前 7 位来判断用户。总之这部分后续会使用 `portrait` 来判断，目前看起来暂时没有问题

3. 主题贴检测的话我有时间单独看一下新情况下的数据返回格式，感谢反馈

**Comment by shitianshiwa** [comment]
关于头像补充
人物名：苏菲·托莱特，作者：甘党，图片来自pixiv网站：https://www.pixiv.net/artworks/51032548
甘党 @amatou111 · 2014年12月30日
日中の吸血鬼さん
https://twitter.com/amatou111/status/549953669958230017

---

**问题1** 
我发现出现样式错误的贴子是被屏蔽掉的主题贴，没有办法直接看到内容，只能给离线网页了。
[转贴_给索菲拉票【邻家的吸血鬼小妹吧】_百度贴吧【邻家索菲吧】_百度贴吧 (2019-12-05 下午7_46_35).zip](https://github.com/FirefoxBar/userscript/files/3926458/_._._.2019-12-05.7_46_35.zip)

http://tieba.baidu.com/photo/p?kw=%E9%82%BB%E5%AE%B6%E7%B4%A2%E8%8F%B2&tid=6149550150&pic_id=456771dce71190ef9612ee70c01b9d16fcfa600c 
这是被屏蔽贴里面的图片链接(题外话：1.贴吧里的图片链接是长期有效的，哪怕原贴被删除+贴子回收站也删除原贴，也依旧可以访问(贴子回收站里的贴子存放超过半年就会被删除 http://tieba.baidu.com/p/6240498071) 。2.即使贴子里发的图片被贴吧屏蔽了，也仍可以通过电脑端贴吧点击该贴没有被屏蔽的图片进去左右翻找到)

---

**问题2**

1. 要制造无用户名的贴吧账号，只需注册时不填写用户名即可。贴吧会自动生成一个名字(贴吧用户_XXXXXX)。至于伪装成正常账号，只要用贴吧app或者用别人找到的https://tieba.baidu.com/n/interact/modifyname 修改昵称即可。
2. 当初是因为全局变量PageData.user里的portrait和贴子里的楼层及楼中楼里表示自己的portrait不一致，所以不使用全局变量里的portrait而采取单独请求 API 获取portrait。而后来发现贴子里右上角最顶的名字里的链接也有和楼层及楼中楼里表示自己的portrait一样的内容，所以就用那个链接进行字符串拆分(split)获得portrait。
而现在是优先使用网页内的portrait，找不到才用api去请求一个，双保险。(仍然不是用全局变量。因为直到看到这里的回复，再去翻看贴吧代码才发现能用了)
 ![贴吧右上角顶](https://user-images.githubusercontent.com/54750485/70226099-907d8d00-1793-11ea-9f11-ccec64369427.png)<a href="" title="点击到个人中心" class="u_username_wrap"></a>。

现在贴子内的portrait几乎都统一了，除了楼中楼回复别人，别人的portrait和别人在楼层留言的portrait还不一致。
---

**问题3**
wap贴吧的贴子有变化

楼. 
 1970-1-1  回复

![wap贴吧被屏蔽的贴子](https://user-images.githubusercontent.com/54750485/70228118-29fa6e00-1797-11ea-9a1d-1eabaaef92d8.png)

**Comment by ccloli** [comment]
其实头像当时找到原图了，不过还是非常感谢介绍。只可惜图收了，番也下了，甚至还下了本画集，但是并没有时间看（比如今日打卡 23:00

1. 这个样式看起来有点奇怪……初步怀疑是左侧的头像一栏过高导致右侧塌陷，不过仔细对比了下自己看到的贴吧页面的 DOM，不知道为什么这个页面里楼层末尾没有清除浮动的 `<div class="clear"></div>`……怀疑是其他扩展或是脚本造成的干扰，也可能被屏蔽的楼层结构不一样？把 `::after` 改成 `::before` 某种程度上可以解决问题，或者可以调整成手动插入一个 DOM（啊能不这样还是不这样好了 = =）

2. 看来还是有坑，周末我研究一下好了，最近太忙没时间看，考虑几种方案都加上，然后按需降级

3. 嗯，大概明白了，可能 `共0贴` 也可以作为判断的标志，非常感谢

**Comment by shitianshiwa** [comment]
返传下只能算能用的项目( 还未使用过Pull requests，github的使用方法还在一点点试中 )

https://github.com/shitianshiwa/baidu-tieba-userscript 
我目前在使用的大部分贴吧脚本&其它脚本。有些脚本蛮奇怪的，例如：网页快速到顶到底+刷新。删贴的脚本是用来对付楼中楼从第二页开始消失的被屏蔽的回复及还被贴吧屏蔽中的201X年甚至200X年的贴子(如果想删除的话)(使用范围：我的贴子http://tieba.baidu.com/i/i/my_tie 和高级搜索http://tieba.baidu.com/f/search/)

fork了
https://github.com/ccloli/Search-By-Image
可以说没动过。计划想办法兼容手机yandex浏览器，该脚本目前无法在手机使用。(计划方法是额外加一个按钮来代替键盘触发）

https://github.com/shitianshiwa/baidu-tieba-userscript/tree/master/%E8%B4%B4%E5%90%A7%E8%B4%B4%E5%AD%90%E5%B1%8F%E8%94%BD%E6%A3%80%E6%B5%8B
这个脚本内的说明可能有点诡异。。！也不清楚了。
目前在使用的是兼容版(检测速度明显慢不少)，下一步计划不明(目前是用计时器来触发检测主题贴和楼层，楼中楼仍使用事件触发)。远期想法是自动列出被屏蔽链接且可定位到点(要想办法弄一个UI来装链接)。最终目标是全局查自己所有贴子是否被屏蔽(离实现很远)。

虽然fork了https://github.com/FirefoxBar/userscript  但还没有动过，

**Comment by ccloli** [comment]
1.1 已发布，尝试解决了下面的几个问题：

1. 贴吧错位的原因是不同贴吧的 HTML 结构不一致（可以理解为虽然外观差不多，但是其实是不同版本的贴吧）。有问题的贴吧表现为页面强制跳转 https，且 HTML 中有大量的 `clearfix` 这个 class，而这个 class 会利用 `::after` 伪元素清除浮动，导致和脚本的样式发生冲突；而目前经常访问的贴吧都是强制跳转 http（以及 URL 会附加 `red_tag` 参数），HTML 中没有 `clearfix` 这个 class，而是在最后单独插入了一个 `<div class="clear"></div>` 来清除浮动；

2. 尝试使用了 `PageData.user.portrait` 来提升适配能力（暂时不考虑再请求一个 API 了，以及右上角的链接其实是异步加载的，不如 `PageData` 可靠）；

3. 匹配了新的主题贴检测方式；

4. 修复了页面检测缓存不生效的问题（缓存可以减少请求次数，不过由于是请求到结果后就不再请求，所以其实结果有可能会变得不可靠）；

5. 页面内的回复贴改为延迟 3 秒后再触发检测（在目前测试的情况下，若在回复后立即请求结果，旧版移动端贴吧页有可能还未同步到数据，结果会误判为贴子被屏蔽）。

还请帮忙确认下上述问题是否已解决，辛苦了。

**Comment by shitianshiwa** [comment]
1、已解决，贴子不再会**错位**
[转贴_给索菲拉票【邻家的吸血鬼小妹吧】_百度贴吧【邻家索菲吧】_百度贴吧 (2019-12-15 下午12_48_59).zip](https://github.com/FirefoxBar/userscript/files/3964581/_._._.2019-12-15.12_48_59.zip)

2、无用户名的贴吧账号已可以使用

3、主题贴列表检测**有效**

4、一般来说，显示出来的贴子不会二次被屏蔽或被删除(即使在屏蔽最严重的那段时候，我也没有见过几次。但还真有过“秋后算账”，发链接为了反和谐，改到难以使用，成功显示后，几个小时后又被屏蔽或者被删了)。如果怕这个的话，就只能加一个浮动固定的清空缓存按钮了。
以下为示例样子:
https://github.com/shitianshiwa/baidu-tieba-userscript/blob/master/%E8%B4%B4%E5%90%A7%E8%B4%B4%E5%AD%90%E5%B1%8F%E8%94%BD%E6%A3%80%E6%B5%8B/%E8%B4%B4%E5%90%A7%E8%B4%B4%E5%AD%90%E5%B1%8F%E8%94%BD%E6%A3%80%E6%B5%8B(%E5%85%BC%E5%AE%B9%E7%89%88)/%E8%B4%B4%E5%90%A7%E8%B4%B4%E5%AD%90%E5%B1%8F%E8%94%BD%E6%A3%80%E6%B5%8B(%E5%85%BC%E5%AE%B9%E7%89%88).user.js#L54
![浮动固定工具栏1](https://user-images.githubusercontent.com/54750485/70857438-6f563280-1f31-11ea-829f-c7f5fbf54e40.png)
![浮动固定工具栏2](https://user-images.githubusercontent.com/54750485/70857440-7715d700-1f31-11ea-959d-6a49d20fda9a.png)
这个功能主要是用来阻止疯狂刷新贴子不停请求或者节省流量?
(我改的贴子屏蔽检测（兼容版）有明显检测延迟，而且应该是要等上一个请求成功后才进行下一个请求的延迟，慢很多，乱刷新应该也问题不大。而且根据浏览器的开发者工具查看网络请求的结果，没有传用户cookie过去，访问太频繁估计就ip会出事？2019-5-24 我曾试过用按键精灵短时间内疯狂刷新电脑端贴吧同一贴几百次而没事。那次是发现贴吧贴子的阅读量可以这样刷上来。可以公开显示阅读量的贴吧客户端版本是v8.1-8.4，更高版本应该仅发贴人自己可见。除了贴吧app外，其它版本贴吧均不可见 https://soft.shouji.com.cn/down/22020.html)

5、已修复，回贴后可以检测新贴是否会被屏蔽（采用百度网盘的链接进行测试，这个链接目前仍是一定会被屏蔽的）

**Comment by ccloli** [comment]
4. 确实是这样的，遇到过贴子回复会正常显示，但是会在十几秒后被删除；也遇到过发表后的回复直接被删除，但是折腾重新发了几次仍被屏蔽的时候，最开始的回复反而吐出来了的情况（一个比较大的例子是 6 月初某天下午 4 点后的贴子全部不可见，两天后又全部吐出来）  
    缓存是存放在 `sessionStorage` 里的，所以这个缓存只会在当前打开的标签页里生效。考虑到贴吧内打开主题贴几乎都是新开标签页的形式，也就是每次打开新贴子都是无缓存的，所以影响应该不大  
    这个脚本的原理就是不传递当前用户的 cookie 获取贴子的显示状态，至于访问过于频繁是否会出事，这个就不确定了。目前没遇到过访问过多被限流的情况，主要还是想要减少访问请求，已经得到结果再发出一次重复请求可能意义不大（尤其是回复后可能所有楼层都会重新触发）  
    至于阅读量的话，在很早以前的贴吧（估计是 7 年前）是有阅读量展示的，不过 UI 更新后就不显示了。当时是有脚本可以直接在新版贴吧里显示阅读量的，不过应该是靠请求旧版贴吧 or 移动端简版贴吧拿到的？这个就不太清楚了，此处 @8qwe24657913

**Comment by 8qwe24657913** [comment]
> 4. 确实是这样的，遇到过贴子回复会正常显示，但是会在十几秒后被删除；也遇到过发表后的回复直接被删除，但是折腾重新发了几次仍被屏蔽的时候，最开始的回复反而吐出来了的情况（一个比较大的例子是 6 月初某天下午 4 点后的贴子全部不可见，两天后又全部吐出来）
>    缓存是存放在 `sessionStorage` 里的，所以这个缓存只会在当前打开的标签页里生效。考虑到贴吧内打开主题贴几乎都是新开标签页的形式，也就是每次打开新贴子都是无缓存的，所以影响应该不大
>    这个脚本的原理就是不传递当前用户的 cookie 获取贴子的显示状态，至于访问过于频繁是否会出事，这个就不确定了。目前没遇到过访问过多被限流的情况，主要还是想要减少访问请求，已经得到结果再发出一次重复请求可能意义不大（尤其是回复后可能所有楼层都会重新触发）
>    至于阅读量的话，在很早以前的贴吧（估计是 7 年前）是有阅读量展示的，不过 UI 更新后就不显示了。当时是有脚本可以直接在新版贴吧里显示阅读量的，不过应该是靠请求旧版贴吧 or 移动端简版贴吧拿到的？这个就不太清楚了，此处 @8qwe24657913

原来 cc 还记得我，感动 :joy:
说正经的：
- 那个脚本用的 API 是 `/i/data/get_pv_by_tids` ，但现在已经 404 了（打开脚本一看这哪个 zz 写的辣鸡代码……哦好像是我写的 :joy:）
- 旧版贴吧在我写那个脚本时就已经不能进了，看脚本最后修改时间的话是 2013 年
- 移动端简版现在连 frs 页（即帖子列表页）都是空的，什么都没有
- 移动端触屏版 api 请求到的直接是 html 内容，里面也没有访问量信息

如果现在还想看访问量的话只能模拟客户端请求，旧版客户端的 API 还比较容易模拟（Greasy Fork 有现成的），新版 API 变了，还上了 protobuf，没有 .proto 文件完全不知道是个什么
虽然也不是不能做，但是我一方面没什么刷贴吧的需求了~~但有时会口嫌体正直地更新一下贴吧扩展~~，另一方面实在是懒得搞（发出咕咕咕的声音）

**Comment by ccloli** [comment]
@8qwe24657913 啧，你刚刚居然换了头像，你不爱学姐了

记得还是记得的，毕竟 @Masotan 经常会提起你 ~~和你的一些不为人知的秘密~~

差不多，现在贴吧基本上是只读模式，顶多随手删几个广告（狐吧后台删贴记录 90% 都是我，破吧吃枣药丸……不对，已经完了），这几天贴吧把过去所有的贴子都放出来了，估计摸鱼时可以去翻翻大家的黑历史怀怀旧 ~~虽然年末怎么可能有时间摸鱼，砖都搬不完~~

访问量其实也没太大意义，毕竟在以前挂个 ProxyHunter 几分钟就能刷上千，而且估计不少人也就是看一下就走

其实屏蔽贴的一个问题就是回复后会顶贴，估摸着是广告点进去翻了半天，结果没找到广告在哪，然后过一段时间再看，会发现广告又吐出来了……

**Comment by 8qwe24657913** [comment]
> @8qwe24657913 啧，你刚刚居然换了头像，你不爱学姐了
> 
> 记得还是记得的，毕竟 @Masotan 经常会提起你 ~和你的一些不为人知的秘密~
> 
> 差不多，现在贴吧基本上是只读模式，顶多随手删几个广告（狐吧后台删贴记录 90% 都是我，破吧吃枣药丸……不对，已经完了），这几天贴吧把过去所有的贴子都放出来了，估计摸鱼时可以去翻翻大家的黑历史怀怀旧 ~虽然年末怎么可能有时间摸鱼，砖都搬不完~
> 
> 访问量其实也没太大意义，毕竟在以前挂个 ProxyHunter 几分钟就能刷上千，而且估计不少人也就是看一下就走
> 
> 其实屏蔽贴的一个问题就是回复后会顶贴，估摸着是广告点进去翻了半天，结果没找到广告在哪，然后过一段时间再看，会发现广告又吐出来了……

关于换头像：我从短暂的人生当中学到一件事……越是单推，就越会发现单推的能力是有极限的……除非超越单推。所以，我不做单推了！cc！！！ ~~其实是被从卑微的谢拉单推强制降格到路人了~~

关于不为人知的秘密：我不记得有和他说过什么秘密啊……是他拿本子 ~~（还是黑车）~~ 过来 ~~性骚扰~~ 被我拒绝后在贴吧黑我性冷淡的事吗……还是他又整了什么新活？ ~~已经在和 @Masotan 对线了，请组织放心~~

贴吧的问题是没什么新鲜血液了，经常是 frs 一整页看下来一个有意思的帖子都没有，也就慢慢淡出了 ~~[黑历史来了](http://tieba.baidu.com/p/4462109528#post_content_87120472991)~~

访问量这种东西一般也没人刷，毕竟刷了没什么意义。访问量高低的区别也就是标题有多吸引人而已（

百度的这个先隐藏后吐出来机制也是够睿智，治不了广告机器，天天给活人找麻烦，不知道有什么意义……减轻服务器压力？

**Comment by shitianshiwa** [comment]
那个贴子阅读量其实不是重点，举那个例子只是因为那是我目前唯一一次做过的刷新实验（估计就是因为可以随便刷，所以才不再公开显示出来）。

由于目前贴吧屏蔽贴子力度巨减，大多数贴子最终应该都可以显示出来，但脚本仍还有作用。（特别是发长文，发链接的，转贴自己贴子的）（目前还见过在发贴阶段就提示内容有问题，请修改后重发的功能）

其实今年还有一个触发广告贴的玩意，那个是可以让贴子永沉顶不起来的。2019-10-9基本解除了这个限制。当然还是有些例外，例如这个还是永沉 https://tieba.baidu.com/p/5613700098 这个贴很特别，无法用大吧的置顶功能顶起来(包括会员置顶。题外话:这个其实也是有bug的，可以小号（什么号都行）试一试这个api“/f/commit/thread/top/madd，/f/commit/thread/top/mcancel"就3个基本参数就行了；话题贴没有那么自由，但吧务组大吧小吧语音小编都能用（如果这个吧没有开放话题贴功能就不能用），是电脑端贴吧专属功能，触屏版只能看到文字话题贴，其它版本贴吧全部不可见)
/f/commit/thread/topic/set  type:3,文字话题，type:4,图片话题
/f/commit/thread/topic/del
'fid':PageData.forum.id,'tbs':PageData.tbs||PageData.user.tbs,'tid':XXXXXXXXXXX,'kw':PageData.forum.name||PageData.forum.forum_name,'ie':utf-8,'type':3

其它收集到的功能也一块发了
bug吧精品区还有几个月前测试可用的隐藏贴代码（只推荐小号用），隐藏AT人
【BUG】◇16-12-16◆〖水♀贴〗电脑端发客户端直播贴代码
https://tieba.baidu.com/p/4901883501
javascript: $.post("/f/commit/thread/add",{ie:"utf-8",kw:PageData.forum.name?PageData.forum.name:PageData.forum.forum_name,fid:PageData.forum.id?PageData.forum.id:PageData.forum.forum_id,tid:0,floor_num:0,rich_text:1,tbs:PageData.tbs,content:prompt("内容"),thread_type:30,title:prompt("标题"),"deal_info[first_cate_id]":52,"deal_info[bid_type]":0,"deal_info[price]":1,"deal_info[contact]":1,"deal_info[second_cate_id]":64,"deal_info[pic][]":"",__type__:"thread"},function(o){if(o.no==0)alert("成功");else alert("失败")},"json");

【BUG】◇16-09-25◆〖教程帖〗第三代隐藏召唤
https://tieba.baidu.com/p/4796238293

https://www.52fisher.cn/category/f12%25e5%25a4%25a7%25e6%25b3%2595%25e5%25a5%25bd.html
小吧恢复帖子代码
April 15, 2016
吧务后台的版本
javascript:var c={fid:PageData.forum.id,tbs:PageData.user.tbs,tid:prompt("请输入要恢复的号"),kw:PageData.forum.name,pid:prompt("请输入要恢复的楼层pid"),dtype:"json",ie:"utf-8",word:PageData.forum.name};$.post("/f/commit/post/delete/cancel",c,function(o){if(o.no!=0)alert("no:"+o.no+"nerr_code:"+o.err_code+"nerror:"+o.error);else alert("OK");},"json");void 0M
帖子页面
javascript:var c={word:PageData.forum.name,tbs:PageData.tbs,list[0][thread_id]:prompt("请输入要恢复的号"),list[0][post_id]:prompt("请输入要恢复的楼层pid"),list[0][post_type]:1,ie:'utf-8'};$.post("http://tieba.baidu.com/bawu2/platform/resPost",c);void 0
**现在只支持恢复主题贴，楼层和楼中楼都不行。**

大吧用wap贴吧的取消精品可以避开手机验证码

**Comment by ccloli** [comment]
@shitianshiwa 

嗯是这样，只是你提到阅读量的时候刚好想起来有这么个脚本

由于不怎么发帖，所以屏蔽力度巨减没怎么体会到，从我最近一个月发的为数不多的贴子和测试用的贴子来看，仅自己可见的命中率大概有 30%。至于修改后重发的那个提示，估摸着有好几年了，在贴吧会自动删除可疑贴子之前就有这玩意了，说有十年历史都不为过

隐藏贴可能有用，不过随着贴吧一轮轮修复 bug + 大批量恢复贴子，估计以前的一些隐藏贴都浮出来了。至于那几个 API，从那个 `/f/commit` 开头来看都感觉有点年头了，那估计是旧版贴吧就有的 API，几乎没怎么修。所有吧务都有权删贴和恢复（包括图片小编语音小编等）这个应该算是比较多人知道的了，记得 @8qwe24657913 应该还写过对应的脚本来着。反正贴吧的一些老接口校验不严，比如之前贴吧申请吧主强制填银行卡和强制绑手机，当时都用控制台 + 本地服务器绕过了，可惜当时的 API 没留下来

看到这么多 API，不知道为什么突然想 @ 某 XSS 面包，不过估计如果真召唤过来的话这个 issue 就变成怀旧帖了，还是算了，虽然可能已经有这种趋势了（顺带一提，如果对后续的回复不感兴趣的话，可以点击右边的 **Unsubscribe** 按钮取消邮件提醒和 GitHub 站内提醒

***

@8qwe24657913 

啧，你让单推索菲的 @shitianshiwa 怎么办，臭 dd，男人没一个好东西

那个黑历史我昨天刚好翻到诶，昨天刚好翻了下那个「Sonico俺の嫁」的过往发言，结果他现在也不单推索尼子了，改玩艾尔之光了，~~果然男人没一个好东西~~

~~至于 @Masotan 的黑历史已经收集不少了，请组织放心~~

没办法，贴吧本来是个不错的产品，从历史上来说比 Reddit 还早，也有不少内容上的沉淀。只不过过来人都知道，贴吧商业化实在说不上成功，外包后又因为各种事件臭了，在现在这种各个 app 靠个性化推送圈住用户形成信息孤岛的时代，贴吧的日子说不上好过

**Comment by 8qwe24657913** [comment]
@ccloli 

贴吧的旧 API 基本上都不怎么鉴权，什么小吧封三天十天、封 36500 天还能恢复帖子，还有什么网页源码暴露用户十进制 IP 地址，楼主删帖 API 不校验 pid 与 tid 一致导致的的跨吧删帖漏洞等等。能发到 BUG 吧的基本都是被玩烂的东西了……（PS: 起手就一个 `var c={...};` 但后面只用到一次 `c` 的这个代码风格就很像 L 神）但新的体系做得还是不错的，鉴权也做得挺好，连发帖都是 UBB 的，没怎么出幺蛾子 ~~虽然不能改变贴吧没人玩了的事实~~

跳过绑银行卡有这么麻烦吗……我当时是直接 `qianbaoBindIframe.sucCallBack()` 的，现在……我试了下怎么申请吧主功能直接关了……

你看无论是 @shitianshiwa 头像的索菲还是你头像的菲娅，这个 issue 下三个人头像都是白发红瞳角色， ~~拆腻子都是白毛控~~ ，本是同根生单推何太急，能推的时候就多去推一推，它难道不香吗？ ~~谁还不是个 DD 了~~ （

贴吧也就用户基数大，把 17 年以前帖子一屏蔽就找不着什么优质内容了，商业化又没有什么有意义的内容上的变化。名声臭不臭倒是其次，个人认为问题还是贴吧的模式不太能适应快餐文化了
