### ISSUE TITLE
百度搜索直链在Super_preloader只有第一页生效

### ISSUE THREAD

**Issue by ju0594** [FirefoxBar/userscript#9]
如题 不知道发在这里有没有人看到

**Comment by wenketel** [comment]
Direct Baidu
https://greasyfork.org/zh-CN/scripts/558-direct-baidu
remove the jump link in BAIDU
https://greasyfork.org/zh-CN/scripts/11915-remove-the-jump-link-in-baidu

**Comment by ju0594** [comment]
@wenketel 用了第二个 可以用啦 谢谢！
